# Updating Gold Standards

If the FST or CGs are updated, we will want to update the gold standards. In the case of disambiguation, if the FST is updated to include more analyses, we will update all gold standard parses affected by this. In the case of dependency parsing, if our CG supports new dependencies, we will want to look at all cases where the parses differ from the previous version.

## Updating disambig gold

To update the disambiguation gold standard, we first rewrite the FST system outputs (cell 1), then diff these with the previous system outputs (cell 2), to focus on manually updating cases where analyses are added/removed .

In [1]:
from grammar_modules.disambiguation import REPO_ROOT
from eval_modules.data_io import read_opd_tsv, build_eval_sample, write_eval_artifacts


TSV_FILE = REPO_ROOT / "evaluation" / "eval_data" / "sample_disambig" / "sample_492.tsv"
FST_BINARY_PATH = REPO_ROOT / "data" / "fst" / "ojibwe20260711.fomabin"
OUTDIR = REPO_ROOT / "evaluation" / "eval_data" / "sample_disambig"

rows = read_opd_tsv(TSV_FILE, has_id_col=True)
write_eval_artifacts(rows, FST_BINARY_PATH, OUTDIR, "20260721_sample_492")

FST file is /Users/matthias/labs/ELF-Lab/ELF-Lab Repos/Ojibwe_Constraint_Grammar/data/fst/ojibwe20260711.fomabin

In [2]:
from grammar_modules.disambiguation import REPO_ROOT
from eval_modules.diff import compare_cg3_readings, diff_table

OLD_FILE = REPO_ROOT / "evaluation" / "eval_data" / "sample_disambig" / "sample_492.txt"
NEW_FILE = REPO_ROOT / "evaluation" / "eval_data" / "sample_disambig" / "20260721_sample_492.txt"
CHANGED_BLOCKS_FILE = REPO_ROOT / "evaluation" / "eval_data" / "out" / "20260721_disambig_to_be_updated.txt"
DIFF_CSV_PATH = "eval_data/out/20260721_disambig_diff.csv"

diff_table(compare_cg3_readings(OLD_FILE, NEW_FILE, CHANGED_BLOCKS_FILE), DIFF_CSV_PATH)

,sent_id,text,token_idx,surface,added,removed
0,2,Gigikenimaa na ezhinaagozid miskwaabiimagoons ...,2,na,na\tPCInterj,
1,2,Gigikenimaa na ezhinaagozid miskwaabiimagoons ...,3,ezhinaagozid,izhinaagozi\tVAI Pcp/ChCnj Pos Neu 3SgProxSubj...,izhinaagozi\tVAI Pcp Pos Neu 3SgProxSubj 3SgPr...
2,2,Gigikenimaa na ezhinaagozid miskwaabiimagoons ...,6,ezhibagizid,izhibagizi\tVAI Pcp/ChCnj Pos Neu 3SgProxSubj ...,izhibagizi\tVAI Pcp Pos Neu 3SgProxSubj 3SgPro...
3,3,Nigichi-zegi'igonaan awe gaa-ojibinigod zhebaa.,3,gaa-ojibinigod,ojibinigo\tPVTense/gii VAI Pcp/ChCnj Pos Neu 3...,ojibinigo\tPVSub/gaa VAI Cnj Pos Neu 3SgProxSu...
4,10,Ingii-inaa ji-giiwed.,2,ji-giiwed,giiwe\tPVTense/ji VAI Cnj Pos Neu 3SgProxSubj,giiwe\tPVTense/daa VAI Cnj Pos Neu 3SgProxSubj...
...,...,...,...,...,...,...
225,481,Biichaa 'i gabeshiwin endazhindaman.,4,endazhindaman,dazhindan\tVTI Pcp/ChCnj Pos Neu 2SgSubj 0SgOb...,
226,485,Ningii-kichiwaabikishin ogiji-asin.,2,ogiji-asin,ogiji-asin\tADVLoc,
227,488,Mamaandaawichigewinini ogii-naagotoon iwe gich...,5,ji-bazigwiimagadinig,bazigwii\tPVTense/ji VAI Der/magad VII Cnj Pos...,bazigwii\tPVTense/daa VAI Der/magad VII Cnj Po...
228,492,Ingii-tebaabamaa biida'adood gaa-mazina'amawid...,3,gaa-mazina'amawid,mazina'amaw\tPVTense/gii VTA Pcp/ChCnj Pos Neu...,mazina'amaw\tPVSub/gaa VTA Cnj Pos Neu 3SgProx...
229,492,Ingii-tebaabamaa biida'adood gaa-mazina'amawid...,5,gaa'-izhi-gaajibani'od,gaajibani'o\tPVTense/gii' PVRel/izhi VAI Pcp/C...,gaajibani'o\tPVTense/gii' PVRel/izhi VAI Pcp P...

## Updating dependency gold

To update the dependency parsing gold standard, we first recompute the system outputs on the disambiguation gold standard (cell 1 in [dependency_eval.ipynb](dependency_eval.ipynb)), and then diff with the old system outputs (cell 3 here) to find where dependencies have been added/changed (usually not removed, as the focus is on increasing coverage).

In [8]:
from grammar_modules.disambiguation import REPO_ROOT
from eval_modules.diff import compare_conllu_outputs, diff_table

OLD_FILE = REPO_ROOT / "evaluation" / "eval_data" / "sample_dep" / "opd_dep_492.conllu"
NEW_FILE = REPO_ROOT / "evaluation" / "eval_data" / "sample_dep" / "20260602_opd_dep_492.conllu"

diff_table(compare_conllu_outputs(OLD_FILE, NEW_FILE), "eval_data/out/20260602_dep_diff.csv")

,sent_id,text,token_id,form,old_head,new_head,old_deprel,new_deprel,changed
0,g14.s2,gego miijiken gaa-boozaag .,3,gaa-boozaag,2,2,dep,obj,deprel
1,g16.s1,nibawaanaa bemaadizid .,2,bemaadizid,1,1,nsubj,obj,deprel
2,g35.s1,minomaasige gaa-zaasakokwaadang moozo-wiiyaas .,2,gaa-zaasakokwaadang,1,3,dep,acl:relcl,head\ndeprel
3,g35.s1,minomaasige gaa-zaasakokwaadang moozo-wiiyaas .,3,moozo-wiiyaas,2,1,obj,dep,head\ndeprel
4,g48.s1,wewiib gagwe-giizhitoon gaa-dazhiikaman gigiki...,3,gaa-dazhiikaman,2,4,dep,acl:relcl,head\ndeprel
5,g48.s1,wewiib gagwe-giizhitoon gaa-dazhiikaman gigiki...,4,gigikinoo'amaagoowin,3,2,obj,dep,head\ndeprel
6,g50.s1,aaniin epiitaagonagaag noongom gaa-biboong .,4,gaa-biboong,2,2,dep,nsubj,deprel
7,g131.s1,maamakaadakamig inendaagozi gaa-anokiitang waa...,3,gaa-anokiitang,2,4,dep,acl:relcl,head\ndeprel
8,g131.s1,maamakaadakamig inendaagozi gaa-anokiitang waa...,4,waakaa'igan,3,2,obj,dep,head\ndeprel
9,g135.s2,ganabaj gii'-niiwezhiwewag gaa-bikwaakwadoonsi...,3,gaa-bikwaakwadoonsikewaad,2,2,dep,nsubj,deprel
10,g137.s1,onjishkawa'o gaa-biidakwazhiwed .,2,gaa-biidakwazhiwed,1,1,dep,nsubj,deprel
11,g143.s1,ingii-adaamaa ditibidaabaanan gaa-ayaad .,3,gaa-ayaad,1,1,nsubj,obj,deprel
12,g194.s1,mamigobidoon nooka'iiwagwaan gaa-mashkawaakwad...,3,gaa-mashkawaakwading,1,2,dep,acl:relcl,head\ndeprel
13,g215.s1,apane ninaanaagadawenimaa noozhis waasa gaa-da...,5,gaa-dazhi-gikinoo'amawind,2,2,dep,obj,deprel
14,g325.s1,niizhoopizowag animoshag gaa-odaabii'aad gaa-m...,4,gaa-maa'ishkang,1,3,dep,nsubj,head\ndeprel
15,g392.s1,indayaawaanaan awe dinowa gaazhagens gaa-biigw...,5,gaa-biigwawed,1,4,dep,acl:relcl,head\ndeprel
16,g407.s1,biiminan gaa-dakigamig .,2,gaa-dakigamig,1,1,dep,obj,deprel
17,g412.s1,ogidadewenamoog abinoojiinyag gaa-gaakaazootaa...,3,gaa-gaakaazootaadiwaad,1,2,dep,acl:relcl,head\ndeprel
18,g425.s1,bekaa bimibizon gaa-gikendanziwan zaaga'igan .,3,gaa-gikendanziwan,2,4,dep,acl:relcl,head\ndeprel
19,g425.s1,bekaa bimibizon gaa-gikendanziwan zaaga'igan .,4,zaaga'igan,3,2,obj,dep,head\ndeprel
20,g439.s1,ningii-tangishkawaa animozhish gaa-bi-gagwe-da...,3,gaa-bi-gagwe-dakwamid,1,2,dep,acl:relcl,head\ndeprel
21,g462.s1,miigwechiwi' awe gaa-gaagiigidod .,3,gaa-gaagiigidod,1,2,dep,acl:relcl,head\ndeprel
22,g492.s1,ingii-tebaabamaa biida'adood gaa-mazina'amawid...,3,gaa-mazina'amawid,1,2,dep,nsubj,head\ndeprel