### Verb selection

In this notebook, we will filter through VTA verb list to assess which verbs have ambiguity (has more than 1 FST analysis)

#### FST-RUNTIME INSTALLATION

Please install fst-runtime (wrapper for FST parser). It requires Python 3.12
- `conda create --name cg3 python=3.12`
- `conda activate cg3`
- `pip install fst-runtime`

In [1]:
from fst_runtime.fst import Fst
import pandas as pd

In [2]:
fst_binary_filename = "../data/fst/ojibwe.att"

fst = Fst(fst_binary_filename)

In [3]:
# test parsing "waabam" (to see)
word = "waabam"
result = fst.up_analysis(wordform=word)
for analysis in result:
    print(analysis)

FstOutput(output_string='waabam+VTA+Imp+Sim+2SgSubj+3SgProxObj', path_weight=None, input_string='waabam')
FstOutput(output_string='waabam+VTA+Imp+Sim+2SgSubj+3PlProxObj', path_weight=None, input_string='waabam')

In [4]:
# load VTA data from csv file
vta_filename = "../data/verbs/VTA_IND.csv"

vta_independence_df = pd.read_csv(vta_filename)

In [5]:
vta_independence_df.head()

,Paradigm,Order,Class,Lemma,Stem,Head,Subject,Object,Mode,Negation,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source,Form3Surface,Form3Split,Form3Source
0,VTA,Ind,VTA_aw,mikaw,mikaw,NONE,0PlSubj,1SgObj,Dub,Neg,nimikaagosiinaadogenan,ni<<mikaa>>gosiinaadogenan,GUESS,NaN,NaN,NaN,NaN,NaN,NaN
1,VTA,Ind,VTA_C,waabam,waabam,NONE,0PlSubj,1SgObj,Dub,Neg,niwaabamigosiinaadogenan,ni<<waabam>>igosiinaadogenan,GUESS,NaN,NaN,NaN,NaN,NaN,NaN
2,VTA,Ind,VTA_Cw,mizho,mizhw1,NONE,0PlSubj,1SgObj,Dub,Neg,nimizhogosiinaadogenan,ni<<mizho>>igosiinaadogenan,GUESS,NaN,NaN,NaN,NaN,NaN,NaN
3,VTA,Ind,VTA_n,miizh,miin1,NONE,0PlSubj,1SgObj,Dub,Neg,nimiinigosiinaadogenan,ni<<miin>>igosiinaadogenan,GUESS,NaN,NaN,NaN,NaN,NaN,NaN
4,VTA,Ind,VTA_s,mawadish,mawadis1,NONE,0PlSubj,1SgObj,Dub,Neg,nimawadisigosiinaadogenan,ni<<mawadis>>igosiinaadogenan,GUESS,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# select word form  column
word_form_list = vta_independence_df["Form1Surface"]
print(word_form_list[:10])
print("Count =", len(word_form_list))

0          nimikaagosiinaadogenan
1        niwaabamigosiinaadogenan
2          nimizhogosiinaadogenan
3          nimiinigosiinaadogenan
4       nimawadisigosiinaadogenan
5       gimikaagosiinaawaadogenan
6     giwaabamigosiinaawaadogenan
7       gimizhogosiinaawaadogenan
8       gimiinigosiinaawaadogenan
9    gimawadisigosiinaawaadogenan
Name: Form1Surface, dtype: object
Count = 3480

In [7]:
ambiguity_list = dict()

In [8]:
max_word_count = -1 # replace to -1 for full list

for word_form in word_form_list[:max_word_count]:
    # print("Processing word form =", word_form)
    fst_analyses = list(fst.up_analysis(wordform=word_form))
    if len(fst_analyses) > 1:
        print("Ambiguity detected.")
        print("Word form =", word_form)
        fst_outputs = [analysis.output_string for analysis in fst_analyses]         
        print("Analyses =", fst_outputs)
        print("-"*10)
        
        # add to result
        ambiguity_list[word_form] = fst_outputs

Ambiguity detected.
Word form = nimizhogosiinaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+1SgObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+1SgObj']
----------
Ambiguity detected.
Word form = gimizhogosiinaawaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+2PlObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+2PlObj']
----------
Ambiguity detected.
Word form = gimizhogosiinaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+2SgObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+2SgObj']
----------
Ambiguity detected.
Word form = omikaagosiinaadogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaadogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaadogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaadogenan
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaawaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3PlProxObj']
----------
Ambiguity detected.
Word form = omikaagosiinaadogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaadogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaadogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaadogenan
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omikaagosiinaadogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaadogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mizhwi+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaadogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'miizh+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaadogenan
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3PlObvObj', 'mawadish+VTA+Ind+Neg+Dub+0PlSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = nimizhogosiiminaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimizhogosiiminaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0PlSubj+InclObj', 'mizho+VTA+Ind+Neg+Dub+0PlSubj+InclObj']
----------
Ambiguity detected.
Word form = nimikaagosiinaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = niwaabamigosiinaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = nimizhogosiinaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+1SgObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = nimiinigosiinaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = nimawadisigosiinaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+3SgProxSubj+ExclObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = gimizhogosiinaawaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+2PlObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+2PlObj']
----------
Ambiguity detected.
Word form = gimikaagosiinaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = giwaabamigosiinaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = gimizhogosiinaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'mizho+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+2SgObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = gimiinigosiinaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = gimawadisigosiinaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+3SgProxSubj+InclObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = omikaagosiinaawaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaawaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaawaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaawaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaawaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omikaagosiinaawaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaawaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaawaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaawaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaawaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0SgSubj+3PlProxObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omikaagosiinaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omikaagosiinaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mikaw+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = owaabamigosiinaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'waabam+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omizhogosiinaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mizhwi+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omiinigosiinaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'miizh+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = omawadisigosiinaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+0SgSubj+3SgProxObj', 'mawadish+VTA+Ind+Neg+Dub+0SgSubj+3SgObvObj']
----------
Ambiguity detected.
Word form = nimizhogosiiminaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimizhogosiiminaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+0SgSubj+InclObj', 'mizho+VTA+Ind+Neg+Dub+0SgSubj+InclObj']
----------
Ambiguity detected.
Word form = gimizhosinooninimwaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+2PlObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+2PlObj']
----------
Ambiguity detected.
Word form = gimizhosinooninaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+2SgObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+2SgObj']
----------
Ambiguity detected.
Word form = nimizhomaasiidogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = nimizhwaasiidogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+3PlProxObj']
----------
Ambiguity detected.
Word form = nimikawimaasiidogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'mikaw+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = niwaabamimaasiidogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'waabam+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = nimizhomaasiidogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'mizhwi+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = nimiinimaasiidogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'miizh+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = nimawadisimaasiidogenan
Analyses = ['mawadish+VTA+Ind+Neg+Dub+1SgSubj+3SgObvObj', 'mawadish+VTA+Ind+Neg+Dub+1SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = nimizhwaasiidog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+1SgSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+1SgSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimikawisiimwaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2PlSubj+1SgObj', 'mikawi+VAI+Ind+Neg+Dub+2PlSubj']
----------
Ambiguity detected.
Word form = gimizhosiimwaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2PlSubj+1SgObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+1SgObj']
----------
Ambiguity detected.
Word form = gimizhomaasiwaawaadogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimizhwaasiwaawaadogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3PlProxObj']
----------
Ambiguity detected.
Word form = gimikawaasiwaawaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mikaw+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = giwaabamaasiwaawaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'waabam+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimizhwaasiwaawaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimiinaasiwaawaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'miizh+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimawadisaasiwaawaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mawadish+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimikawaasiwaawaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mikaw+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = giwaabamaasiwaawaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'waabam+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimizhwaasiwaawaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mizhwi+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimiinaasiwaawaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'miizh+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimawadisaasiwaawaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+2PlSubj+3SgObvObj', 'mawadish+VTA+Ind+Neg+Dub+2PlSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimikawisiinaamaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mikaw+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = giwaabamisiinaamaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'waabam+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimizhosiinaamaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mizhwi+VTA+Ind+Neg+Dub+2PlSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimiizhisiinaamaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'miizh+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimawadishisiinaamaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mawadish+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimikawisiinaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2SgSubj+1SgObj', 'mikawi+VAI+Ind+Neg+Dub+2SgSubj']
----------
Ambiguity detected.
Word form = gimizhosiinaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+1SgObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+1SgObj']
----------
Ambiguity detected.
Word form = gimizhomaasiidogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimizhwaasiidogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+3PlProxObj']
----------
Ambiguity detected.
Word form = gimikawimaasiidogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'mikaw+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = giwaabamimaasiidogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'waabam+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimizhomaasiidogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'mizhwi+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimiinimaasiidogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'miizh+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimawadisimaasiidogenan
Analyses = ['mawadish+VTA+Ind+Neg+Dub+2SgSubj+3SgObvObj', 'mawadish+VTA+Ind+Neg+Dub+2SgSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = gimizhwaasiidog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = gimikawisiinaamaadog
Analyses = ['mikaw+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mikaw+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = giwaabamisiinaamaadog
Analyses = ['waabam+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'waabam+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimizhosiinaamaadog
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mizhwi+VTA+Ind+Neg+Dub+2PlSubj+ExclObj', 'mizho+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimiizhisiinaamaadog
Analyses = ['miizh+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'miizh+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = gimawadishisiinaamaadog
Analyses = ['mawadish+VTA+Ind+Neg+Dub+2SgSubj+ExclObj', 'mawadish+VTA+Ind+Neg+Dub+2PlSubj+ExclObj']
----------
Ambiguity detected.
Word form = omizhogosiiwaadogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlObvSubj+3PlProxObj', 'mizho+VTA+Ind+Neg+Dub+3PlObvSubj+3PlProxObj']
----------
Ambiguity detected.
Word form = omizhogosiidogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlObvSubj+3SgProxObj', 'mizho+VTA+Ind+Neg+Dub+3PlObvSubj+3SgProxObj']
----------
Ambiguity detected.
Word form = nimizhogosiidogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+1SgObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+1SgObj']
----------
Ambiguity detected.
Word form = gimizhogosiiwaadogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+2PlObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+2PlObj']
----------
Ambiguity detected.
Word form = gimizhogosiidogenag
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+2SgObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+2SgObj']
----------
Ambiguity detected.
Word form = omizhwaasiwaawaadogena'
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omikawaasiwaawaadogenan
Analyses = ['mikaw+VTA+Ind+Neg+Dub+3PlProxSubj+3SgObvObj', 'mikaw+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = owaabamaasiwaawaadogenan
Analyses = ['waabam+VTA+Ind+Neg+Dub+3PlProxSubj+3SgObvObj', 'waabam+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omizhwaasiwaawaadogenan
Analyses = ['mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+3SgObvObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+3SgObvObj', 'mizhwi+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj', 'mizho+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omiinaasiwaawaadogenan
Analyses = ['miizh+VTA+Ind+Neg+Dub+3PlProxSubj+3SgObvObj', 'miizh+VTA+Ind+Neg+Dub+3PlProxSubj+3PlObvObj']
----------
Ambiguity detected.
Word form = omawadisaasiwaawaadogenan

In [9]:
# create pandas dataframe to hold output
output_df = pd.DataFrame(
    {"wordform": ambiguity_list.keys(),
     "fst_analyses": ambiguity_list.values(),
    }
    )
output_df.head()

,wordform,fst_analyses
0,nimizhogosiinaadogenan,"[mizhwi+VTA+Ind+Neg+Dub+0PlSubj+1SgObj, mizho+..."
1,gimizhogosiinaawaadogenan,"[mizhwi+VTA+Ind+Neg+Dub+0PlSubj+2PlObj, mizho+..."
2,gimizhogosiinaadogenan,"[mizhwi+VTA+Ind+Neg+Dub+0PlSubj+2SgObj, mizho+..."
3,omikaagosiinaadogenan,"[mikaw+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj, mik..."
4,owaabamigosiinaadogenan,"[waabam+VTA+Ind+Neg+Dub+0PlSubj+3SgProxObj, wa..."

In [10]:
# write to output file
output_filename = "../data/verbs/VTA_IND_AMBIGUITY_LIST.csv"
print("Writing ambiguity list to file =", output_filename)
output_df.to_csv(output_filename)
print("Completed")

Writing ambiguity list to file = ../data/verbs/VTA_IND_AMBIGUITY_LIST.csv
Completed